name: local-chat

services:
  web:
    build:
      context: web
      target: runner
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - source: web_cert
        target: site.crt
      - source: web_key
        target: site.key
    networks:
      - local_chat

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    # ports:
    #   - 11434:11434
    networks:
      - local_chat

volumes:
  ollama_data: {}

networks:
  local_chat: {}

configs:
  nginx_conf:
    file: ./web/nginx.conf

secrets:
  web_cert:
    file: ./web/certs/localhost.pem
  web_key:
    file: ./web/certs/localhost-key.pem
