name: local-chat

services:
  web:
    build: web
    ports:
      - 80:80
    networks:
      - local_chat

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - local_chat

volumes:
  ollama_data: {}

networks:
  local_chat: {}
